version: '3.6'

services:
  ebay-api:
    image: ebayapi:latest
    environment:
      EBAY_APP_ID_SBOX: ''
      EBAY_APP_SECRET_SBOX: ''
      EBAY_APP_ID: ''
      EBAY_APP_SECRET: ''
      EBAY_MODE: 'PRODUCTION'
      EBAY_BASE_URL_SBOX: 'https://api.sandbox.ebay.com/buy/browse/v1/item_summary/'
      EBAY_BASE_URL: 'https://api.ebay.com/buy/browse/v1/item_summary/'
      EBAY_TOKEN_SBOX_URL: 'https://api.sandbox.ebay.com/identity/v1/oauth2/token'
      EBAY_TOKEN_URL: 'https://api.ebay.com/identity/v1/oauth2/token'
      EBAY_RESULT_COUNT: 3
      SERVER_PORT: 3010
    ports:
      - 3010:3010
  email-api:
    image: emailapi:latest
    environment:
      SERVER_PORT: 3009
      EMAIL_SERVER: 'smtp.ethereal.email'
      EMAIL_USER: 'abigayle92@ethereal.email'
      EMAIL_PASS: '9CvWVcq9dQ964HsquN'
      EMAIL_PORT: 587
      EMAIL_SECURE: 'false'
      EMAIL_ORIGIN: 'Byron App <byron@example.com>'
      EMAIL_SUBJECT: 'Byron Term: '
    ports:
      - 3009:3009
  mongo-api:
    image: mongoapi:latest
    environment:
      SERVER_PORT: 3008
      DB_URL: 'mongodb://localhost/monitor'
    ports:
      - 3008:3008
    command: ['node', 'dist/main.js']
  byron-app:
    image: byronapp:latest
    environment:
      NODE_ENV: 'production'
      EBAY_API: 'ebay-api'
      EMAIL_API: 'email-api'
      MONGO_API: 'mongo-api'
    ports:
      - 80:80
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      - ebay-api
      - email-api
      - mongo-api
  server-byron:
    image: serverbyron:latest
    environment:
      EBAY_API: 'http://ebay-api:3010'
      EMAIL_API: 'http://email-api:3009'
      MONGO_API: 'http://mongo-api:3008'
      SERVER_MIN: 1
    command: ['node', 'index.js']
    depends_on:
      - ebay-api
      - email-api
      - mongo-api
